### ISSUE TITLE
Support for Powermock

### ISSUE THREAD

**Issue by littledot** [crittercism/dexmaker#3]
[0]: https://code.google.com/p/powermock/
I am trying to incorporate [Powermock][0] as a dependency for my Android tests using the following build.gradle configuration:

```
dependencies{
    compile 'com.android.support:appcompat-v7:21.0.+'
    androidTestCompile('org.mockito:mockito-core:1.9.5')
    androidTestCompile('com.google.dexmaker:dexmaker:1.2')
    androidTestCompile('com.google.dexmaker:dexmaker-mockito:1.2')
    androidTestCompile('org.powermock:powermock-module-junit4:1.5.5') {
        exclude module: 'junit'
    }
    androidTestCompile('org.powermock:powermock-api-mockito:1.5.5') {
        exclude module: 'mockito-all'
    }
}
```

However, the compiler is complaining that 
```
Error:Gradle: Execution failed for task ':app:packageDebugTest'.
> Duplicate files copied in APK mockito-extensions/org.mockito.plugins.MockMaker
  	File 1: ~/.gradle/caches/modules-2/files-2.1/com.google.dexmaker/dexmaker-mockito/1.2/b99884a4c6ef6335ba376f79aa79632b2421c17c/dexmaker-mockito-1.2.jar
  	File 2: ~/.gradle/caches/modules-2/files-2.1/com.google.dexmaker/dexmaker-mockito/1.2/b99884a4c6ef6335ba376f79aa79632b2421c17c/dexmaker-mockito-1.2.jar
```

Looking into the jar structure, I noticed that both Dexmaker and Powermock declare a `MockMaker` in `mockito-extensions`
![img](http://i.imgur.com/JOPn7zk.png?1)

What is a MockMaker? How do they differ? 
And the most important question: Is it possible to get Powermock to work nicely with Dexmaker?

Thanks in advance. Any help would be greatly appreciated.

**Comment by gauthamchandra** [comment]
@littledot Are you running Instrumentation tests that run on a device or pure Java unit tests that run in a standard JVM? 

If you are talking the former, then even if dexmaker fixed this issue, you would still have trouble.

[This issue explains it nicely](https://github.com/jayway/powermock/issues/594)

> PowerMock won't work on Android if you run it
on a device since PowerMock is using JVM byte code manipulation. It will
work if you run it on a JVM though.

I mention this because your example shows you using `androidTestCompile` instead of `testCompile`.

**Comment by Moonant** [comment]
so sad

**Comment by littledot** [comment]
Thanks for clarifying~
